"""Add image_url to restaurants

Revision ID: 390eeaba8abe
Revises: 11fcbe671147
Create Date: 2025-06-29 02:00:11.425577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390eeaba8abe'
down_revision: Union[str, Sequence[str], None] = '11fcbe671147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'image_url')
    # ### end Alembic commands ###
