"""Add gallery and menu_images to restaurants

Revision ID: 4364a8440007
Revises: 390eeaba8abe
Create Date: 2025-06-29 02:05:34.540975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4364a8440007'
down_revision: Union[str, Sequence[str], None] = '390eeaba8abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('gallery', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('menu_images', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'menu_images')
    op.drop_column('restaurants', 'gallery')
    # ### end Alembic commands ###
