"""update_booking_guests_field

Revision ID: a7222efdcdce
Revises: f350f3f99e2b
Create Date: 2025-06-29 19:15:50.343041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7222efdcdce'
down_revision: Union[str, Sequence[str], None] = 'f350f3f99e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('guests', sa.Integer(), nullable=False))
    op.drop_column('bookings', 'guests_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('guests_count', sa.INTEGER(), nullable=False))
    op.drop_column('bookings', 'guests')
    # ### end Alembic commands ###
