"""add_restaurant_working_hours

Revision ID: f350f3f99e2b
Revises: 472c93f32005
Create Date: 2025-06-29 19:05:43.148995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f350f3f99e2b'
down_revision: Union[str, Sequence[str], None] = '472c93f32005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('opening_time', sa.Time(), nullable=False))
    op.add_column('restaurants', sa.Column('closing_time', sa.Time(), nullable=False))
    op.add_column('restaurants', sa.Column('slot_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'slot_duration')
    op.drop_column('restaurants', 'closing_time')
    op.drop_column('restaurants', 'opening_time')
    # ### end Alembic commands ###
