"""change_booking_status_to_string

Revision ID: fb6dc2409cc3
Revises: 5fd0816ea3c1
Create Date: 2025-06-29 19:45:31.554939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6dc2409cc3'
down_revision: Union[str, Sequence[str], None] = '5fd0816ea3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
